import { Request, Response, NextFunction } from 'express'
import { AppError } from './errorHandler'

/** Header the browser sends with every profile/result request. */
export const DEVICE_HEADER = 'x-device-id'

// A random id generated by the browser (a UUID in practice). Only the shape is checked here.
const DEVICE_ID_PATTERN = /^[A-Za-z0-9-]{16,64}$/

/**
 * Profiles belong to the browser that created them. Every profile and result
 * request must carry that browser's private device id, which handlers read from
 * `res.locals.deviceId` and use to scope all queries.
 */
export const requireDevice = (req: Request, res: Response, next: NextFunction): void => {
  const value = req.header(DEVICE_HEADER)
  if (!value || !DEVICE_ID_PATTERN.test(value)) {
    next(new AppError(400, 'A valid device id is required'))
    return
  }
  res.locals.deviceId = value
  next()
}

export const getDeviceId = (res: Response): string => res.locals.deviceId as string
